---
title: "gambling_OR,Utah"
author: "Zhichao Shan"
date: "2021/5/17"
output: html_document
---

```{r}
library(pacman)
p_load(readr,dplyr,stargazer,sandwich,tidyverse,broom)
setwd("C:/Users/Alienware/Desktop/EC/EC510_crime/Rwork/EC510_crime")
gou <- read.csv('Gambling Or,Utah.csv')
```

```{r}
#create dummy variable year over 2013
gou <- mutate(gou, after = ifelse(gou$Year>=1985, 1, 0))
```

```{r}
#create dummy variable for interation effect
gou <- mutate(gou, treatafter = after*Treat)
summary(gou)
```

```{r}
treated_ou <- subset(gou, gou$Treat==1)
summary(treated_ou)
```

```{r}
goue <- ggplot(gou, aes(x=Year, y=Murder)) +  geom_point(aes(colour = Treat), size =2) +
  geom_vline(xintercept = 1985, lty = 4)
goue <- goue + labs(title = "Murder and Time", x = "Year", y = "Murder")
goue + geom_line(aes(colour = Treat, group = Treat))
```

```{r}
ge_ouM <- lm(Murder ~ Treat+after+treatafter+Year+Population, data=gou)
tidy(ge_ouM)
```


```{r}
goue_p <- ggplot(gou, aes(x=Year, y=Property)) +  geom_point(aes(colour = Treat), size =2) +
  geom_vline(xintercept = 1985, lty = 4)
goue_p <- goue_p + labs(title = "Property and Time", x = "Year", y = "Property")
goue_p + geom_line(aes(colour = Treat, group = Treat))
```

```{r}
ge_ouP <- lm(Property ~ Treat+after+treatafter+Year+Population, data=gou)
tidy(ge_ouP)
```


```{r}
goue_r <- ggplot(gou, aes(x=Year, y=Robbery)) +  geom_point(aes(colour = Treat), size =2) +
  geom_vline(xintercept = 1985, lty = 4)
goue_r <- goue_r + labs(title = "Robbery and Time", x = "Year", y = "Robbery")
goue_r + geom_line(aes(colour = Treat, group = Treat))
```

```{r}
ge_ouR <- lm(Robbery ~ Treat+after+treatafter+Year+Population, data=gou)
tidy(ge_ouR)
```


```{r}
goue_t <- ggplot(gou, aes(x=Year, y=Larceny_Theft)) +  geom_point(aes(colour = Treat), size =2) +
  geom_vline(xintercept = 1985, lty = 4)
goue_t <- goue_t + labs(title = "Theft and Time", x = "Year", y = "Theft")
goue_t + geom_line(aes(colour = Treat, group = Treat))
```

```{r}
ge_ouT <- lm(Larceny_Theft ~ Treat+after+treatafter+Year+Population, data=gou)
tidy(ge_ouT)
```


```{r}
ge_ouI <- lm(Index ~ Treat+after+treatafter+Year+Population, data=gou)
tidy(ge_ouI)
```



